// Mocks generated by Mockito 5.4.6 from annotations
// in phynd_app/test/presentation/screens/library_page/sections/favorite_video_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i15;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:phynd_app/core/utils/api_service.dart' as _i2;
import 'package:phynd_app/data/models/payload/game_payload_model.dart' as _i10;
import 'package:phynd_app/data/models/response/favorite_content_model.dart'
    as _i11;
import 'package:phynd_app/data/models/response/game_list_model.dart' as _i9;
import 'package:phynd_app/data/models/response/game_model.dart' as _i3;
import 'package:phynd_app/data/models/response/like_follow_model.dart' as _i4;
import 'package:phynd_app/data/models/response/video_model.dart' as _i12;
import 'package:phynd_app/data/services/game_service.dart' as _i6;
import 'package:video_player/src/closed_caption_file.dart' as _i14;
import 'package:video_player/video_player.dart' as _i5;
import 'package:video_player_platform_interface/video_player_platform_interface.dart'
    as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiService_0 extends _i1.SmartFake implements _i2.ApiService {
  _FakeApiService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGameDetails_1 extends _i1.SmartFake implements _i3.GameDetails {
  _FakeGameDetails_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLikeFollowStatus_2 extends _i1.SmartFake
    implements _i4.LikeFollowStatus {
  _FakeLikeFollowStatus_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVideoPlayerValue_3 extends _i1.SmartFake
    implements _i5.VideoPlayerValue {
  _FakeVideoPlayerValue_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GameService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameService extends _i1.Mock implements _i6.GameService {
  MockGameService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseURL => (super.noSuchMethod(
        Invocation.getter(#baseURL),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#baseURL),
        ),
      ) as String);

  @override
  _i2.ApiService get api => (super.noSuchMethod(
        Invocation.getter(#api),
        returnValue: _FakeApiService_0(
          this,
          Invocation.getter(#api),
        ),
      ) as _i2.ApiService);

  @override
  set api(_i2.ApiService? _api) => super.noSuchMethod(
        Invocation.setter(
          #api,
          _api,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<_i3.GameDetails> getGameDetails({required String? gameSlug}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGameDetails,
          [],
          {#gameSlug: gameSlug},
        ),
        returnValue: _i8.Future<_i3.GameDetails>.value(_FakeGameDetails_1(
          this,
          Invocation.method(
            #getGameDetails,
            [],
            {#gameSlug: gameSlug},
          ),
        )),
      ) as _i8.Future<_i3.GameDetails>);

  @override
  _i8.Future<({int count, List<_i9.GameItem> data})> getMarketplaceGames({
    int? page = 1,
    int? limit = 12,
    _i10.GamePayload? filters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMarketplaceGames,
          [],
          {
            #page: page,
            #limit: limit,
            #filters: filters,
          },
        ),
        returnValue: _i8.Future<({int count, List<_i9.GameItem> data})>.value(
            (count: 0, data: <_i9.GameItem>[])),
      ) as _i8.Future<({int count, List<_i9.GameItem> data})>);

  @override
  _i8.Future<void> followGame({required String? gameSlug}) =>
      (super.noSuchMethod(
        Invocation.method(
          #followGame,
          [],
          {#gameSlug: gameSlug},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> favoriteSaveGame({
    required String? gameSlug,
    bool? favorite,
    bool? saved,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #favoriteSaveGame,
          [],
          {
            #gameSlug: gameSlug,
            #favorite: favorite,
            #saved: saved,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> removeFavoriteSaveGame({
    required String? gameSlug,
    bool? favorite,
    bool? saved,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFavoriteSaveGame,
          [],
          {
            #gameSlug: gameSlug,
            #favorite: favorite,
            #saved: saved,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> unFollowGame({required String? gameSlug}) =>
      (super.noSuchMethod(
        Invocation.method(
          #unFollowGame,
          [],
          {#gameSlug: gameSlug},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i4.LikeFollowStatus> checkLikeFollowGameStatus(
          {required String? gameSlug}) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkLikeFollowGameStatus,
          [],
          {#gameSlug: gameSlug},
        ),
        returnValue:
            _i8.Future<_i4.LikeFollowStatus>.value(_FakeLikeFollowStatus_2(
          this,
          Invocation.method(
            #checkLikeFollowGameStatus,
            [],
            {#gameSlug: gameSlug},
          ),
        )),
      ) as _i8.Future<_i4.LikeFollowStatus>);

  @override
  _i8.Future<
      ({
        int currentPage,
        List<_i3.FavoriteGame> data,
        int remainingPages,
        int total,
        int totalPage
      })> getFavoriteGames({
    int? page = 1,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavoriteGames,
          [],
          {
            #page: page,
            #limit: limit,
          },
        ),
        returnValue: _i8.Future<
            ({
              int currentPage,
              List<_i3.FavoriteGame> data,
              int remainingPages,
              int total,
              int totalPage
            })>.value((
          currentPage: 0,
          data: <_i3.FavoriteGame>[],
          remainingPages: 0,
          total: 0,
          totalPage: 0
        )),
      ) as _i8.Future<
          ({
            int currentPage,
            List<_i3.FavoriteGame> data,
            int remainingPages,
            int total,
            int totalPage
          })>);

  @override
  _i8.Future<
      ({
        int currentPage,
        List<_i3.FavoriteGame> data,
        int remainingPages,
        int total,
        int totalPage
      })> getSavedGames({
    int? page = 1,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSavedGames,
          [],
          {
            #page: page,
            #limit: limit,
          },
        ),
        returnValue: _i8.Future<
            ({
              int currentPage,
              List<_i3.FavoriteGame> data,
              int remainingPages,
              int total,
              int totalPage
            })>.value((
          currentPage: 0,
          data: <_i3.FavoriteGame>[],
          remainingPages: 0,
          total: 0,
          totalPage: 0
        )),
      ) as _i8.Future<
          ({
            int currentPage,
            List<_i3.FavoriteGame> data,
            int remainingPages,
            int total,
            int totalPage
          })>);

  @override
  _i8.Future<
      ({
        int currentPage,
        List<_i11.FavoriteContent> data,
        int remainingPages,
        int total,
        int totalPage
      })> getSavedContent({
    int? page = 1,
    int? limit = 10,
    required String contentType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSavedContent,
          [],
          {
            #page: page,
            #limit: limit,
            #contentType: contentType,
          },
        ),
        returnValue: _i8.Future<
            ({
              int currentPage,
              List<_i11.FavoriteContent> data,
              int remainingPages,
              int total,
              int totalPage
            })>.value((
          currentPage: 0,
          data: <_i11.FavoriteContent>[],
          remainingPages: 0,
          total: 0,
          totalPage: 0
        )),
      ) as _i8.Future<
          ({
            int currentPage,
            List<_i11.FavoriteContent> data,
            int remainingPages,
            int total,
            int totalPage
          })>);

  @override
  _i8.Future<
      ({
        int currentPage,
        List<_i11.FavoriteContent> data,
        int remainingPages,
        int total,
        int totalPage
      })> getFavoriteContent({
    int? page = 1,
    int? limit = 10,
    required String contentType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavoriteContent,
          [],
          {
            #page: page,
            #limit: limit,
            #contentType: contentType,
          },
        ),
        returnValue: _i8.Future<
            ({
              int currentPage,
              List<_i11.FavoriteContent> data,
              int remainingPages,
              int total,
              int totalPage
            })>.value((
          currentPage: 0,
          data: <_i11.FavoriteContent>[],
          remainingPages: 0,
          total: 0,
          totalPage: 0
        )),
      ) as _i8.Future<
          ({
            int currentPage,
            List<_i11.FavoriteContent> data,
            int remainingPages,
            int total,
            int totalPage
          })>);

  @override
  _i8.Future<
      ({
        int currentPage,
        List<_i12.FavoriteVideo> data,
        int remainingPages,
        int total,
        int totalPage
      })> getFavoriteVideos({
    int? page = 1,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavoriteVideos,
          [],
          {
            #page: page,
            #limit: limit,
          },
        ),
        returnValue: _i8.Future<
            ({
              int currentPage,
              List<_i12.FavoriteVideo> data,
              int remainingPages,
              int total,
              int totalPage
            })>.value((
          currentPage: 0,
          data: <_i12.FavoriteVideo>[],
          remainingPages: 0,
          total: 0,
          totalPage: 0
        )),
      ) as _i8.Future<
          ({
            int currentPage,
            List<_i12.FavoriteVideo> data,
            int remainingPages,
            int total,
            int totalPage
          })>);
}

/// A class which mocks [VideoPlayerController].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoPlayerController extends _i1.Mock
    implements _i5.VideoPlayerController {
  MockVideoPlayerController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get dataSource => (super.noSuchMethod(
        Invocation.getter(#dataSource),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#dataSource),
        ),
      ) as String);

  @override
  Map<String, String> get httpHeaders => (super.noSuchMethod(
        Invocation.getter(#httpHeaders),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  _i13.DataSourceType get dataSourceType => (super.noSuchMethod(
        Invocation.getter(#dataSourceType),
        returnValue: _i13.DataSourceType.asset,
      ) as _i13.DataSourceType);

  @override
  int get textureId => (super.noSuchMethod(
        Invocation.getter(#textureId),
        returnValue: 0,
      ) as int);

  @override
  _i8.Future<Duration?> get position => (super.noSuchMethod(
        Invocation.getter(#position),
        returnValue: _i8.Future<Duration?>.value(),
      ) as _i8.Future<Duration?>);

  @override
  _i5.VideoPlayerValue get value => (super.noSuchMethod(
        Invocation.getter(#value),
        returnValue: _FakeVideoPlayerValue_3(
          this,
          Invocation.getter(#value),
        ),
      ) as _i5.VideoPlayerValue);

  @override
  set value(_i5.VideoPlayerValue? newValue) => super.noSuchMethod(
        Invocation.setter(
          #value,
          newValue,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> play() => (super.noSuchMethod(
        Invocation.method(
          #play,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setLooping(bool? looping) => (super.noSuchMethod(
        Invocation.method(
          #setLooping,
          [looping],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> pause() => (super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> seekTo(Duration? position) => (super.noSuchMethod(
        Invocation.method(
          #seekTo,
          [position],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setVolume(double? volume) => (super.noSuchMethod(
        Invocation.method(
          #setVolume,
          [volume],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setPlaybackSpeed(double? speed) => (super.noSuchMethod(
        Invocation.method(
          #setPlaybackSpeed,
          [speed],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void setCaptionOffset(Duration? offset) => super.noSuchMethod(
        Invocation.method(
          #setCaptionOffset,
          [offset],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> setClosedCaptionFile(
          _i8.Future<_i14.ClosedCaptionFile>? closedCaptionFile) =>
      (super.noSuchMethod(
        Invocation.method(
          #setClosedCaptionFile,
          [closedCaptionFile],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
